<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
<meta name="GENERATOR" content="TtH 3.80">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
 <style type="text/css"> div.p { margin-top: 7pt;}</style>
 <style type="text/css"><!--
 td div.comp { margin-top: -0.6ex; margin-bottom: -1ex;}
 td div.comb { margin-top: -0.6ex; margin-bottom: -.6ex;}
 td div.hrcomp { line-height: 0.9; margin-top: -0.8ex; margin-bottom: -1ex;}
 td div.norm {line-height:normal;}
 span.roman {font-family: serif; font-style: normal; font-weight: normal;} 
 span.overacc2 {position: relative;  left: .8em; top: -1.2ex;}
 span.overacc1 {position: relative;  left: .6em; top: -1.2ex;} --></style>
<title>Try-catch statement</title>
</head>

<body>
 <h2><a name="tth_sEc14">
14</a>&nbsp;&nbsp;Try-catch statement</h2>

<div class="p"><!----></div>
Statement &nbsp;TryStatement <br />
TryStatement &nbsp;"try" BlockStatement Catch Finally <br />
             \ -  "try" BlockStatement Catch Finally <br />
Catch &nbsp;"catch" "(" Formal ")" BlockStatement <br />
Finally &nbsp;"finally" BlockStatement <br />


<div class="p"><!----></div>
Exceptions are handled with a "try" statement.
A "try" statement consists of a "try" block, zero or more
"catch" blocks, and an optional "finally" block.

<div class="p"><!----></div>
First, the "try" block is evaluated.  If the block throws an
exception, control transfers to the first matching "catch"
block, if any.  A "catch" matches if the value of the
exception thrown is a subclass of the "catch" block's formal
parameter type.

<div class="p"><!----></div>
The "finally" block, if present, is evaluated on all normal
and exceptional control-flow paths from the "try" block.
If the "try" block completes normally
or via a "return", a "break", or a
"continue" statement, 
the "finally"
block is evaluated, and then control resumes at
the statement following the "try" statement, at the branch target, or at
the caller as appropriate.
If the "try" block completes
exceptionally, the "finally" block is evaluated after the
matching "catch" block, if any, and then the
exception is rethrown.

<div class="p"><!----></div>
</body>
</html>